### ISSUE TITLE
update authors list

### ISSUE THREAD

**Issue by stitam** [EDiLD/webchem_paper#12]

**Comment by andschar** [comment]
Is this paper work in progress? Do you want people to contribute? I could add parts for the [ChEBI ](https://www.ebi.ac.uk/chebi) contribution I made to webchem, if necessary.

**Comment by eduardszoecs** [comment]
Feel free to join andreas, paper is actually already accepted ^^ just needs to be updated...

**Comment by andschar** [comment]
Ok, didn't expect that^^ I can file a PR in the next one or two weeks. Do you have a deadline?

**Comment by stitam** [comment]
Yes, this is work in progress. I don't think we have a deadline, but I think it would be great if we could finish the update by the end of January. If you send your e-mail address to webchem at ropensci dot org I will add you to the e-mail flow and to our slack channel.
